from __future__ import annotations

from pathlib import Path
from typing import Callable, Iterable

from .ast import Branch, InstructionCall, Node, Routine, Rung

# Helper functions
def RUNG(*nodes: Node) -> Rung: ...
def BRANCH(*branches: Iterable[Node]) -> Branch: ...
def ROUTINE(
    *,
    name: str,
    rungs: Iterable[Rung] = ...,
    program: str | None = None,
    source_path: str | Path | None = None,
) -> Routine: ...

def load_routine_from_source(
    source: str, *, symbol_name: str | None = None
) -> Routine: ...

# Dynamically generated instruction functions (opcodes)
# These are created by _instruction() for each opcode in OPERAND_COUNTS
def ADD(*operands: object) -> InstructionCall: ...
def AFI(*operands: object) -> InstructionCall: ...
def CMP(*operands: object) -> InstructionCall: ...
def COP(*operands: object) -> InstructionCall: ...
def CPT(*operands: object) -> InstructionCall: ...
def CTU(*operands: object) -> InstructionCall: ...
def EQU(*operands: object) -> InstructionCall: ...
def FFL(*operands: object) -> InstructionCall: ...
def FFU(*operands: object) -> InstructionCall: ...
def FLL(*operands: object) -> InstructionCall: ...
def GEQ(*operands: object) -> InstructionCall: ...
def GRT(*operands: object) -> InstructionCall: ...
def JMP(*operands: object) -> InstructionCall: ...
def JSR(*operands: object) -> InstructionCall: ...
def LBL(*operands: object) -> InstructionCall: ...
def LEQ(*operands: object) -> InstructionCall: ...
def LES(*operands: object) -> InstructionCall: ...
def LIM(*operands: object) -> InstructionCall: ...
def MAFR(*operands: object) -> InstructionCall: ...
def MAJ(*operands: object) -> InstructionCall: ...
def MAM(*operands: object) -> InstructionCall: ...
def MAS(*operands: object) -> InstructionCall: ...
def MCCM(*operands: object) -> InstructionCall: ...
def MCCD(*operands: object) -> InstructionCall: ...
def MCLM(*operands: object) -> InstructionCall: ...
def MCS(*operands: object) -> InstructionCall: ...
def MOD(*operands: object) -> InstructionCall: ...
def MOV(*operands: object) -> InstructionCall: ...
def MRP(*operands: object) -> InstructionCall: ...
def MSF(*operands: object) -> InstructionCall: ...
def MSO(*operands: object) -> InstructionCall: ...
def NEQ(*operands: object) -> InstructionCall: ...
def NOP(*operands: object) -> InstructionCall: ...
def ONS(*operands: object) -> InstructionCall: ...
def OSF(*operands: object) -> InstructionCall: ...
def OSR(*operands: object) -> InstructionCall: ...
def OTE(*operands: object) -> InstructionCall: ...
def OTL(*operands: object) -> InstructionCall: ...
def OTU(*operands: object) -> InstructionCall: ...
def PID(*operands: object) -> InstructionCall: ...
def RES(*operands: object) -> InstructionCall: ...
def SFX(*operands: object) -> InstructionCall: ...
def SLS(*operands: object) -> InstructionCall: ...
def TON(*operands: object) -> InstructionCall: ...
def TRN(*operands: object) -> InstructionCall: ...
def XIC(*operands: object) -> InstructionCall: ...
def XIO(*operands: object) -> InstructionCall: ...
