"""Golden-fixture parity test for `circle_pair_tangent_pairs`.

Loads each JSON fixture under `tests/golden/geometry/circle_pair_tangent/`
and confirms the new Rust implementation in
`dune_geometry::wire::circle_pair_tangent_pairs` (exposed as
`dune_geometry.circle_pair_tangent_pairs`) matches the legacy Python
implementation captured in the fixture.

Fixtures are regenerated by
`scripts/generate_circle_pair_tangent_fixtures.py`.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

dune_geometry = pytest.importorskip("dune_geometry")


_FIXTURE_DIR = (
    Path(__file__).resolve().parents[1] / "golden" / "geometry" / "circle_pair_tangent"
)
_TOL = 1e-9


def _fixture_files() -> list[Path]:
    return sorted(_FIXTURE_DIR.glob("*.json"))


def _pairs_close(actual: tuple, expected: tuple) -> bool:
    (afx, afy), (asx, asy) = actual
    (efx, efy), (esx, esy) = expected
    return (
        abs(afx - efx) <= _TOL
        and abs(afy - efy) <= _TOL
        and abs(asx - esx) <= _TOL
        and abs(asy - esy) <= _TOL
    )


@pytest.mark.parametrize("fixture_path", _fixture_files(), ids=lambda p: p.stem)
def test_circle_pair_tangent_matches_python_reference(fixture_path: Path) -> None:
    fixture = json.loads(fixture_path.read_text(encoding="utf-8"))
    first = fixture["first"]
    second = fixture["second"]
    actual = dune_geometry.circle_pair_tangent_pairs(
        (first["cx"], first["cy"]),
        first["r"],
        (second["cx"], second["cy"]),
        second["r"],
    )
    expected = [
        (
            (entry["first_xy"][0], entry["first_xy"][1]),
            (entry["second_xy"][0], entry["second_xy"][1]),
        )
        for entry in fixture["tangent_pairs"]
    ]
    assert len(actual) == len(expected), (
        f"{fixture_path.name}: tangent count {len(actual)} != reference {len(expected)}"
    )
    # Order must match — both implementations enumerate sign combinations in
    # the same order, so this is a tighter contract than set-equality.
    for index, (a, e) in enumerate(zip(actual, expected)):
        assert _pairs_close(a, e), (
            f"{fixture_path.name}: pair[{index}] {a} differs from reference {e}"
        )
