"""Golden-fixture parity test for `select_tangent_solution`.

Loads each JSON fixture under
`tests/golden/geometry/select_tangent_solution/` and confirms the new
Rust implementation in
`dune_geometry::wire::select_tangent_solution` (exposed as
`dune_geometry.select_tangent_solution`) matches the legacy Python
implementation captured in the fixture.

Fixtures are regenerated by
`scripts/generate_select_tangent_solution_fixtures.py`.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

dune_geometry = pytest.importorskip("dune_geometry")


_FIXTURE_DIR = (
    Path(__file__).resolve().parents[1]
    / "golden"
    / "geometry"
    / "select_tangent_solution"
)
_TOL = 1e-9


def _fixture_files() -> list[Path]:
    return sorted(_FIXTURE_DIR.glob("*.json"))


def _candidates_from_fixture(
    fixture: dict,
) -> list[tuple[tuple[float, float], tuple[float, float]]]:
    return [
        (
            (entry["first_xy"][0], entry["first_xy"][1]),
            (entry["second_xy"][0], entry["second_xy"][1]),
        )
        for entry in fixture["candidates"]
    ]


def _bounds_from_fixture(fixture: dict) -> tuple[float, float, float, float]:
    bounds = fixture["transfer_bounds"]
    return (bounds["left"], bounds["top"], bounds["right"], bounds["bottom"])


def _maybe_point(value: dict | None) -> tuple[float, float] | None:
    if value is None:
        return None
    return (value["x"], value["y"])


def _maybe_sides(value: list | None) -> tuple[str, str] | None:
    if value is None:
        return None
    return (value[0], value[1])


def _close(actual: tuple[float, float], expected: tuple[float, float]) -> bool:
    return abs(actual[0] - expected[0]) <= _TOL and abs(actual[1] - expected[1]) <= _TOL


@pytest.mark.parametrize("fixture_path", _fixture_files(), ids=lambda p: p.stem)
def test_select_tangent_solution_matches_python_reference(fixture_path: Path) -> None:
    fixture = json.loads(fixture_path.read_text(encoding="utf-8"))
    candidates = _candidates_from_fixture(fixture)
    bounds = _bounds_from_fixture(fixture)
    anchor_point = _maybe_point(fixture["anchor_pin_point"])
    anchor_sides = _maybe_sides(fixture["anchor_tangent_sides"])
    wrapped_point = _maybe_point(fixture["wrapped_pin_point"])
    wrapped_sides = _maybe_sides(fixture["wrapped_tangent_sides"])

    if fixture["error"] is not None:
        with pytest.raises(ValueError):
            dune_geometry.select_tangent_solution(
                candidates,
                bounds,
                anchor_pin_point=anchor_point,
                anchor_tangent_sides=anchor_sides,
                wrapped_pin_point=wrapped_point,
                wrapped_tangent_sides=wrapped_sides,
            )
        return

    actual = dune_geometry.select_tangent_solution(
        candidates,
        bounds,
        anchor_pin_point=anchor_point,
        anchor_tangent_sides=anchor_sides,
        wrapped_pin_point=wrapped_point,
        wrapped_tangent_sides=wrapped_sides,
    )
    expected = fixture["selected"]
    assert _close(actual[0], (expected["tangent_a"][0], expected["tangent_a"][1])), (
        f"{fixture_path.name}: tangent_a {actual[0]} != {expected['tangent_a']}"
    )
    assert _close(actual[1], (expected["tangent_b"][0], expected["tangent_b"][1])), (
        f"{fixture_path.name}: tangent_b {actual[1]} != {expected['tangent_b']}"
    )
    assert _close(
        actual[2], (expected["clipped_start"][0], expected["clipped_start"][1])
    ), f"{fixture_path.name}: clipped_start {actual[2]} != {expected['clipped_start']}"
    assert _close(
        actual[3], (expected["clipped_end"][0], expected["clipped_end"][1])
    ), f"{fixture_path.name}: clipped_end {actual[3]} != {expected['clipped_end']}"
