"""Golden-fixture parity test for `compute_arm_corrected_outbound`.

Loads each JSON fixture under
`tests/golden/geometry/compute_arm_corrected_outbound/` and confirms the
new Rust implementation in
`dune_geometry::wire::compute_arm_corrected_outbound` (exposed as
`dune_geometry.compute_arm_corrected_outbound`) matches the legacy
Python implementation captured in the fixture.

Fixtures are regenerated by
`scripts/generate_compute_arm_corrected_outbound_fixtures.py`.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

dune_geometry = pytest.importorskip("dune_geometry")


_FIXTURE_DIR = (
    Path(__file__).resolve().parents[1]
    / "golden"
    / "geometry"
    / "compute_arm_corrected_outbound"
)
_TOL = 1e-9


def _fixture_files() -> list[Path]:
    return sorted(_FIXTURE_DIR.glob("*.json"))


def _close(actual: tuple[float, float], expected: list[float]) -> bool:
    return abs(actual[0] - expected[0]) <= _TOL and abs(actual[1] - expected[1]) <= _TOL


@pytest.mark.parametrize("fixture_path", _fixture_files(), ids=lambda p: p.stem)
def test_compute_arm_corrected_outbound_matches_python_reference(
    fixture_path: Path,
) -> None:
    fixture = json.loads(fixture_path.read_text(encoding="utf-8"))
    bounds = fixture["transfer_bounds"]
    transfer = (bounds["left"], bounds["top"], bounds["right"], bounds["bottom"])
    roller_offsets = (
        tuple(fixture["roller_arm_y_offsets"])
        if fixture["roller_arm_y_offsets"] is not None
        else None
    )
    args = (
        (fixture["anchor_pin_point"]["x"], fixture["anchor_pin_point"]["y"]),
        (fixture["target_pin_point"]["x"], fixture["target_pin_point"]["y"]),
        (fixture["tangent_point_a"]["x"], fixture["tangent_point_a"]["y"]),
        (fixture["tangent_point_b"]["x"], fixture["tangent_point_b"]["y"]),
        transfer,
        fixture["head_arm_length"],
        fixture["head_roller_radius"],
        fixture["head_roller_gap"],
        roller_offsets,
    )

    if fixture["error"] is not None:
        with pytest.raises(ValueError):
            dune_geometry.compute_arm_corrected_outbound(*args)
        return

    outbound, head_center, roller_index, quadrant = (
        dune_geometry.compute_arm_corrected_outbound(*args)
    )
    expected = fixture["selected"]
    assert _close(outbound, expected["corrected_outbound"]), (
        f"{fixture_path.name}: corrected_outbound {outbound} != {expected['corrected_outbound']}"
    )
    assert _close(head_center, expected["corrected_head_center"]), (
        f"{fixture_path.name}: corrected_head_center {head_center} != {expected['corrected_head_center']}"
    )
    assert roller_index == expected["roller_index"], (
        f"{fixture_path.name}: roller_index {roller_index} != {expected['roller_index']}"
    )
    assert quadrant == expected["quadrant"], (
        f"{fixture_path.name}: quadrant {quadrant} != {expected['quadrant']}"
    )
