"""Golden-fixture parity test for `tangent_for_pin_pair`.

Loads each JSON fixture under
`tests/golden/geometry/tangent_for_pin_pair/` and confirms the new Rust
implementation in `dune_geometry::wire::tangent_for_pin_pair` (exposed
as `dune_geometry.tangent_for_pin_pair`) matches the legacy Python
`tangent_sides` + `circle_pair_tangent_pairs` reference captured in the
fixture.

Fixtures are regenerated by
`scripts/generate_tangent_for_pin_pair_fixtures.py`.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

dune_geometry = pytest.importorskip("dune_geometry")


_FIXTURE_DIR = (
    Path(__file__).resolve().parents[1] / "golden" / "geometry" / "tangent_for_pin_pair"
)
_TOL = 1e-9


def _fixture_files() -> list[Path]:
    return sorted(_FIXTURE_DIR.glob("*.json"))


def _pin_from_fixture(layer: str, pin_name: str) -> object:
    side = pin_name[0]
    number = int(pin_name[1:])
    return dune_geometry.Pin(layer, side, number)


@pytest.mark.parametrize("fixture_path", _fixture_files(), ids=lambda p: p.stem)
def test_tangent_for_pin_pair_matches_python_reference(fixture_path: Path) -> None:
    fixture = json.loads(fixture_path.read_text(encoding="utf-8"))
    layer = fixture["layer"]
    anchor = _pin_from_fixture(layer, fixture["anchor"]["pin"])
    target = _pin_from_fixture(layer, fixture["target"]["pin"])
    actual_a, actual_b = dune_geometry.tangent_for_pin_pair(
        anchor,
        tuple(fixture["anchor"]["xy"]),
        fixture["anchor"]["r"],
        target,
        tuple(fixture["target"]["xy"]),
        fixture["target"]["r"],
    )
    expected_a = tuple(fixture["tangent_a"])
    expected_b = tuple(fixture["tangent_b"])
    assert abs(actual_a[0] - expected_a[0]) <= _TOL, fixture_path.name
    assert abs(actual_a[1] - expected_a[1]) <= _TOL, fixture_path.name
    assert abs(actual_b[0] - expected_b[0]) <= _TOL, fixture_path.name
    assert abs(actual_b[1] - expected_b[1]) <= _TOL, fixture_path.name
