"""Golden-fixture parity test for `actual_wire_point_from_machine_target`.

Loads each JSON fixture under
`tests/golden/geometry/actual_wire_point/` and confirms the new Rust
implementation in
`dune_geometry::wire::actual_wire_point_from_machine_target` (exposed
as `dune_geometry.actual_wire_point_from_machine_target`) matches the
legacy Python implementation captured in the fixture.

Fixtures are regenerated by
`scripts/generate_actual_wire_point_fixtures.py`.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

dune_geometry = pytest.importorskip("dune_geometry")


_FIXTURE_DIR = (
    Path(__file__).resolve().parents[1] / "golden" / "geometry" / "actual_wire_point"
)
_TOL = 1e-9


def _fixture_files() -> list[Path]:
    return sorted(_FIXTURE_DIR.glob("*.json"))


@pytest.mark.parametrize("fixture_path", _fixture_files(), ids=lambda p: p.stem)
def test_actual_wire_point_matches_python_reference(fixture_path: Path) -> None:
    fixture = json.loads(fixture_path.read_text(encoding="utf-8"))
    wire_x, wire_y = dune_geometry.actual_wire_point_from_machine_target(
        (fixture["final_head_xy"]["x"], fixture["final_head_xy"]["y"]),
        (
            fixture["compensated_anchor_xy"]["x"],
            fixture["compensated_anchor_xy"]["y"],
        ),
        fixture["anchor_z"],
        fixture["head_z"],
        fixture["head_arm_length"],
        fixture["head_roller_radius"],
        fixture["head_roller_gap"],
    )
    expected_x, expected_y = fixture["wire_point"]
    assert abs(wire_x - expected_x) <= _TOL, (
        f"{fixture_path.name}: wire_x {wire_x} != {expected_x}"
    )
    assert abs(wire_y - expected_y) <= _TOL, (
        f"{fixture_path.name}: wire_y {wire_y} != {expected_y}"
    )
