// Generates `src/schema_generated.rs` from `dune_winder/plc/tags.toml`.
//
// Re-run when the schema changes. The generated file declares one `pub static`
// `TagId` per tag, with capability and CIP type baked in at compile time.

use serde::Deserialize;
use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::PathBuf;

#[derive(Debug, Deserialize)]
struct Schema {
    #[serde(default)]
    tag: BTreeMap<String, TagSpec>,
    #[serde(default)]
    bundle: BTreeMap<String, BundleSpec>,
}

#[derive(Debug, Deserialize, Clone)]
struct TagSpec {
    cip: String,
    #[serde(rename = "type")]
    rust_type: String,
    capability: String,
    tier: String,
    #[serde(default)]
    #[allow(dead_code)]
    default: Option<toml::Value>,
    #[serde(default)]
    doc: String,
}

#[derive(Debug, Deserialize)]
struct BundleSpec {
    members: Vec<String>,
    tags: BTreeMap<String, BundleTagSpec>,
}

#[derive(Debug, Deserialize, Clone)]
struct BundleTagSpec {
    name: String,
    cip: String,
    #[serde(rename = "type")]
    rust_type: String,
    capability: String,
    tier: String,
    #[serde(default)]
    default: Option<toml::Value>,
    #[serde(default)]
    doc: String,
}

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let schema_path = manifest_dir
        .join("../../../dune_winder/plc/tags.toml")
        .canonicalize()
        .expect("tags.toml not found");

    println!("cargo:rerun-if-changed={}", schema_path.display());
    println!("cargo:rerun-if-changed=build.rs");

    let toml_text = fs::read_to_string(&schema_path).expect("read tags.toml");
    let schema: Schema = toml::from_str(&toml_text).expect("parse tags.toml");

    let mut all_tags: Vec<(String, TagSpec)> = schema.tag.into_iter().collect();
    for (_bundle_name, bundle) in schema.bundle {
        for member in &bundle.members {
            for (_tag_key, t) in &bundle.tags {
                let name = t.name.replace("{member}", member);
                let doc = t.doc.replace("{member}", member);
                let spec = TagSpec {
                    cip: t.cip.clone(),
                    rust_type: t.rust_type.clone(),
                    capability: t.capability.clone(),
                    tier: t.tier.clone(),
                    default: t.default.clone(),
                    doc,
                };
                all_tags.push((name, spec));
            }
        }
    }

    let mut out = String::new();
    out.push_str("// AUTOGENERATED by build.rs from dune_winder/plc/tags.toml. Do not edit.\n\n");
    out.push_str("use crate::capability::{Read, Write, ReadWrite};\n");
    out.push_str("use crate::snapshot::{CipType, Tier};\n");
    out.push_str("use crate::tag::{ErasedTagId, TagId};\n\n");
    out.push_str("pub struct Tags;\n\n");
    out.push_str("impl Tags {\n");

    let mut erased_entries = Vec::new();

    for (name, spec) in &all_tags {
        let cap_ty = match spec.capability.as_str() {
            "read" => "Read",
            "write" => "Write",
            "read_write" => "ReadWrite",
            other => panic!("unknown capability {other} for tag {name}"),
        };
        let tier_variant = match spec.tier.as_str() {
            "critical" => "Critical",
            "high" => "High",
            "normal" => "Normal",
            "slow" => "Slow",
            "on_demand" => "OnDemand",
            other => panic!("unknown tier {other} for tag {name}"),
        };
        let cip_variant = cip_to_variant(&spec.cip);
        let rust_ty = &spec.rust_type;
        let const_ident = sanitize_ident(name);
        let const_name = const_ident.to_uppercase();

        if !spec.doc.is_empty() {
            out.push_str(&format!("    /// {}\n", spec.doc));
        }
        out.push_str(&format!(
            "    pub const {const}: TagId<{ty}, {cap}> = TagId::new(\"{name}\", CipType::{cip}, Tier::{tier});\n",
            const = const_name,
            ty = rust_ty,
            cap = cap_ty,
            name = name,
            cip = cip_variant,
            tier = tier_variant,
        ));

        erased_entries.push((const_name.clone(), name.clone(), cip_variant, tier_variant));
    }

    out.push_str("}\n\n");

    out.push_str("pub fn all_tags() -> &'static [ErasedTagId] {\n");
    out.push_str("    &[\n");
    for (_const_name, name, cip_variant, tier_variant) in &erased_entries {
        out.push_str(&format!(
            "        ErasedTagId {{ name: \"{name}\", cip: CipType::{cip}, tier: Tier::{tier} }},\n",
            name = name,
            cip = cip_variant,
            tier = tier_variant,
        ));
    }
    out.push_str("    ]\n");
    out.push_str("}\n");

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    fs::write(out_dir.join("schema_generated.rs"), out).expect("write schema_generated.rs");
}

fn cip_to_variant(cip: &str) -> &'static str {
    match cip {
        "BOOL" => "Bool",
        "SINT" => "Sint",
        "INT" => "Int",
        "DINT" => "Dint",
        "REAL" => "Real",
        "REAL[2]" => "RealArray2",
        "REAL[3]" => "RealArray3",
        other => panic!("unknown CIP type {other}"),
    }
}

fn sanitize_ident(name: &str) -> String {
    name.chars()
        .map(|c| if c.is_alphanumeric() { c } else { '_' })
        .collect()
}
